### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'REQUIREMENTS.txt'

### ISSUE THREAD

**Issue by amici-ursi** [j0ack/discirc#2]
```
amici@laptop:~/Desktop$ pip3 install discirc
Collecting discirc
  Downloading discirc-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-htpp49c8/discirc/setup.py", line 26, in <module>
        for line in open('REQUIREMENTS.txt', 'r'):
    FileNotFoundError: [Errno 2] No such file or directory: 'REQUIREMENTS.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-htpp49c8/discirc/
```

**Comment by j0ack** [comment]
Thanks for the report.

**Comment by amici-ursi** [comment]
No problem. Are you accepting bug reports / enhancement requests?

**Comment by j0ack** [comment]
Sure feel free to fill issue or new feature request.

I also accepts PR with new features or bug fix.
