### ISSUE TITLE
ImportError: cannot import name 'TYPE_CHECKING'

### ISSUE THREAD

**Issue by monabat79** [j0ack/discirc#9]
```
C:\Users\Admin
λ discirc
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\Scripts\discirc.exe\__main__.py", line 5, in <module>
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\discirc\launcher.py", line 31, in <module>
    from discirc.irc_bot import IRCBot
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\discirc\irc_bot.py", line 24, in <module>
    import bottom
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\bottom\__init__.py", line 2, in <module>
    from bottom.client import Client
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\bottom\client.py", line 5, in <module>
    from bottom.protocol import Protocol
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\bottom\protocol.py", line 4, in <module>
    from typing import Optional, TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING'
```

Running on Python version `3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]`, and on a `Windows-7-6.1.7601-SP1` machine.

Just configured the bot and tried to run it, but it doesn't work.

**Comment by j0ack** [comment]
It seems the issue is concerning [bottom](https://github.com/numberoverzero/bottom) rather than discirc itself. 

How did you install the app (from git or from pypi) ?

**Comment by monabat79** [comment]
Installed `discirc` from pypi.

**Comment by j0ack** [comment]
Can you tell me after reinstalling from pypi if the bug remains ?
It seems that it runs well on linux after installation.

**Comment by monabat79** [comment]
The same problem still occured after reinstalling...

**Comment by j0ack** [comment]
You can try to install bottom from pypi and check if `import bottom`give you the same results.
If this is the case you should try to report the issue to bottom itself.

**Comment by monabat79** [comment]
```py
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bottom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\bottom\__init__.py", line 2, in <module>
    from bottom.client import Client
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\bottom\client.py", line 5, in <module>
    from bottom.protocol import Protocol
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\bottom\protocol.py", line 4, in <module>
    from typing import Optional, TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING'
>>>
```
Yup, it's probably bottom. Will go report it.
